#+TITLE: MonomialTranslations.jl

MonomialTranslations.jl is the supplementary Julia module to our [[LINK][paper]]. It allows the user to verify our results (up to error due to random numbers).
* Installation
Ensure [[https://github.com/yuvraj-singh-math/julia-odebase][OscarODEbase]] is installed first.

#+begin_src bash
git clone https://github.com/yuvraj-singh-math/monomial-translation.git
cd monomial-translation
#+end_src
Run ~julia~ and activate the module:
#+begin_src julia
julia> ]activate .
#+end_src
* Usage
Include the module:
#+begin_src julia
julia> using MonomialTranslations
#+end_src
The supported ODEbase systems are automatically loaded. The module exports two functions corresponding to the two experiments detailed in the paper.
** Finding criteria for good embeddings
This corresponds to Section 3 of the paper. The score data is reproduced by calling ~produce_data()~ with all arguments left to their default values. The scores for each perturbation are dumped in ~out/perturb_info~.

After this, run ~src/process.jl~ to produce the score results dumped in csv format.
** Finding good embeddings
This corresponds to Section 4 of the paper. Run ~align.jl~ in the root of the repository, and the results are outputted to ~alignment-results.csv~. The figure in the paper can be reproduced by running ~csvtotex.jl~.
